sonar.projectKey=mfozmen_promotion-management-api
sonar.organization=mfozmen
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=src/server.ts
