import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildSchemaDdl } from '@src/shared/db/build-schema-ddl.js';
import { MIGRATIONS_FOLDER } from '@src/shared/db/migrate.js';

async function migrationsFolder(entries: { tag: string; sql: string }[]): Promise<string> {
  const folder = await mkdtemp(join(tmpdir(), 'pma-ddl-'));
  await mkdir(join(folder, 'meta'));
  await writeFile(
    join(folder, 'meta', '_journal.json'),
    JSON.stringify({ entries: entries.map(({ tag }, idx) => ({ idx, tag })) }),
  );
  await Promise.all(entries.map(({ tag, sql }) => writeFile(join(folder, `${tag}.sql`), sql)));
  return folder;
}

describe('buildSchemaDdl', () => {
  it('concatenates the migrations in journal order under a heading each', async () => {
    const folder = await migrationsFolder([
      { tag: '0000_first', sql: 'CREATE TABLE a ();' },
      { tag: '0001_second', sql: 'CREATE TABLE b ();' },
    ]);

    const ddl = await buildSchemaDdl(folder);

    expect(ddl).toContain(
      '-- 0000_first.sql\nCREATE TABLE a ();\n\n-- 0001_second.sql\nCREATE TABLE b ();',
    );
  });

  it('follows the journal rather than the names on disk', async () => {
    const folder = await migrationsFolder([
      { tag: '0001_second', sql: 'CREATE TABLE b ();' },
      { tag: '0000_first', sql: 'CREATE TABLE a ();' },
    ]);

    expect(await buildSchemaDdl(folder)).toContain('CREATE TABLE b ();\n\n-- 0000_first.sql');
  });

  it('drops the statement breakpoints, whether or not they sit on their own line', async () => {
    const folder = await migrationsFolder([
      {
        tag: '0000_both',
        sql: 'CREATE TABLE a ();--> statement-breakpoint\nCREATE TABLE b ();\n--> statement-breakpoint\nCREATE TABLE c ();',
      },
    ]);

    expect(await buildSchemaDdl(folder)).toContain(
      'CREATE TABLE a ();\nCREATE TABLE b ();\nCREATE TABLE c ();',
    );
    expect(await buildSchemaDdl(folder)).not.toContain('statement-breakpoint');
  });

  it('says what it is, so a later ALTER TABLE is not read as missing from the design', async () => {
    const folder = await migrationsFolder([{ tag: '0000_first', sql: 'CREATE TABLE a ();' }]);

    expect(await buildSchemaDdl(folder)).toMatch(/^-- Generated by `npm run db:export-ddl`/);
  });

  it('writes LF whatever line endings the checkout handed it', async () => {
    const folder = await migrationsFolder([
      { tag: '0000_crlf', sql: 'CREATE TABLE a ();\r\nCREATE TABLE b ();\r\n' },
    ]);

    // Otherwise the export carries the worktree's line endings into a file `.gitattributes`
    // pins to LF, and the comparison below is red on a fresh Windows checkout and nowhere else.
    expect(await buildSchemaDdl(folder)).not.toContain('\r');
  });

  // The export is only a deliverable while it is the migrations: this is the comparison that
  // fails when one lands without `npm run db:export-ddl` being run. The committed side is read
  // as LF so a CRLF worktree reports the drift it has, not a re-export it is not missing.
  it('matches the committed docs/schema.sql', async () => {
    const committed = await readFile(
      new URL('../../../../docs/schema.sql', import.meta.url),
      'utf8',
    );

    expect(await buildSchemaDdl(MIGRATIONS_FOLDER)).toBe(committed.replaceAll('\r\n', '\n'));
  });
});
