import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

const HEADER = `-- Generated by \`npm run db:export-ddl\`; edits here are overwritten.
-- The migration script in journal order, not a folded resulting schema: a later ALTER TABLE
-- stands as its own statement below the CREATE TABLE it changes, and the seed rows a migration
-- inserts are part of it.
`;

interface Journal {
  entries: { tag: string }[];
}

/** The DDL deliverable, derived from the migrations so it cannot describe a schema they do not. */
export async function buildSchemaDdl(migrationsFolder: string): Promise<string> {
  const journal = JSON.parse(
    await readFile(join(migrationsFolder, 'meta', '_journal.json'), 'utf8'),
  ) as Journal;

  const migrations = await Promise.all(
    journal.entries.map(async ({ tag }) => {
      const sql = await readFile(join(migrationsFolder, `${tag}.sql`), 'utf8');
      return `-- ${tag}.sql\n${sql.replaceAll(/\s*--> statement-breakpoint/g, '').trim()}\n`;
    }),
  );

  return `${HEADER}\n${migrations.join('\n')}`;
}
