-- Generated by `npm run db:export-ddl`; edits here are overwritten.
-- The migration script in journal order, not a folded resulting schema: a later ALTER TABLE
-- stands as its own statement below the CREATE TABLE it changes, and the seed rows a migration
-- inserts are part of it.

-- 0000_write_store.sql
-- btree_gist is what lets the two promotion exclusion constraints below mix `=` on a scalar
-- with `&&` on a range; drizzle-kit generates no extension statements.
CREATE EXTENSION IF NOT EXISTS "btree_gist";
CREATE TYPE "public"."chunk_status" AS ENUM('pending', 'running', 'done', 'failed');
CREATE TYPE "public"."ingestion_status" AS ENUM('running', 'paused', 'completed', 'failed', 'aborted');
CREATE TYPE "public"."pricing_rule_type" AS ENUM('ingestion', 'promotion');
CREATE TYPE "public"."promotion_discount_type" AS ENUM('percentage', 'fixed');
CREATE TYPE "public"."promotion_status" AS ENUM('draft', 'active', 'cancelled');
CREATE TABLE "ingestion_chunks" (
	"job_id" bigint NOT NULL,
	"chunk_index" integer NOT NULL,
	"start_offset" bigint NOT NULL,
	"end_offset" bigint NOT NULL,
	"next_offset" bigint NOT NULL,
	"lease_until" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"failures" integer DEFAULT 0 NOT NULL,
	"rows_processed" integer DEFAULT 0 NOT NULL,
	"rows_rejected" integer DEFAULT 0 NOT NULL,
	"status" "chunk_status" DEFAULT 'pending' NOT NULL,
	"last_error" text,
	CONSTRAINT "ingestion_chunks_job_id_chunk_index_pk" PRIMARY KEY("job_id","chunk_index")
);
CREATE TABLE "ingestion_jobs" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "ingestion_jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"vendor" text NOT NULL,
	"file_ref" text NOT NULL,
	"file_sha256" text NOT NULL,
	"file_size_bytes" bigint NOT NULL,
	"chunks_total" integer NOT NULL,
	"chunks_done" integer DEFAULT 0 NOT NULL,
	"rows_processed" bigint DEFAULT 0 NOT NULL,
	"rows_rejected" bigint DEFAULT 0 NOT NULL,
	"status" "ingestion_status" DEFAULT 'running' NOT NULL,
	"last_error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ingestion_jobs_file_sha256_unique" UNIQUE("file_sha256")
);
CREATE TABLE "pricing_rules" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "pricing_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"type" "pricing_rule_type" NOT NULL,
	"name" text NOT NULL,
	"conditions" jsonb NOT NULL,
	"event" jsonb NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "pricing_rules_name_unique" UNIQUE("name")
);
CREATE TABLE "products" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sku" text NOT NULL,
	"name" text NOT NULL,
	"category" text NOT NULL,
	"base_price_cents" bigint NOT NULL,
	"stock_quantity" integer NOT NULL,
	"pricing_rules_version" bigint,
	"ingest_job_id" bigint,
	"ingest_source_offset" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "products_sku_unique" UNIQUE("sku"),
	CONSTRAINT "products_base_price_cents_check" CHECK ("products"."base_price_cents" >= 0),
	CONSTRAINT "products_stock_quantity_check" CHECK ("products"."stock_quantity" >= 0),
	CONSTRAINT "products_ingest_provenance_check" CHECK (("products"."ingest_job_id" is null) = ("products"."ingest_source_offset" is null))
);
CREATE TABLE "promotions" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "promotions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"discount_type" "promotion_discount_type" NOT NULL,
	"value" integer NOT NULL,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone NOT NULL,
	"product_id" bigint,
	"category" text,
	"status" "promotion_status" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"cancelled_at" timestamp with time zone,
	CONSTRAINT "promotions_window_check" CHECK ("promotions"."ends_at" > "promotions"."starts_at"),
	CONSTRAINT "promotions_value_check" CHECK ("promotions"."value" > 0),
	CONSTRAINT "promotions_percentage_value_check" CHECK ("promotions"."discount_type" <> 'percentage' or "promotions"."value" <= 10000),
	CONSTRAINT "promotions_active_target_check" CHECK ("promotions"."status" <> 'active' or ("promotions"."product_id" is null) <> ("promotions"."category" is null)),
	CONSTRAINT "promotions_draft_target_check" CHECK ("promotions"."status" <> 'draft' or ("promotions"."product_id" is null and "promotions"."category" is null))
);
CREATE TABLE "reconciler_state" (
	"id" boolean PRIMARY KEY DEFAULT true NOT NULL,
	"last_boundary_sweep_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "reconciler_state_single_row_check" CHECK ("reconciler_state"."id")
);
ALTER TABLE "ingestion_chunks" ADD CONSTRAINT "ingestion_chunks_job_id_ingestion_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."ingestion_jobs"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "promotions" ADD CONSTRAINT "promotions_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;
CREATE UNIQUE INDEX "ingestion_jobs_one_running_per_vendor" ON "ingestion_jobs" USING btree ("vendor") WHERE "ingestion_jobs"."status" in ('running', 'paused');
CREATE INDEX "pricing_rules_active_idx" ON "pricing_rules" USING btree ("type","priority" DESC NULLS LAST) WHERE "pricing_rules"."active";
CREATE INDEX "products_category_id_idx" ON "products" USING btree ("category","id");
-- At most one active product-level promotion per product per instant, and the same per
-- category. Drizzle has no builder for exclusion constraints, so they are written by hand;
-- both GiST indexes also serve the point lookup
-- "target = $1 and tstzrange(starts_at, ends_at) @> now()". gist_int8_ops offers only
-- =(bigint, bigint), so a product_id compared against an integer drops out of the index
-- condition into a heap filter; keep the operand bigint.
ALTER TABLE "promotions" ADD CONSTRAINT "promotions_no_overlapping_active_product" EXCLUDE USING gist ("product_id" WITH =, tstzrange("starts_at", "ends_at") WITH &&) WHERE ("status" = 'active' AND "product_id" IS NOT NULL);
ALTER TABLE "promotions" ADD CONSTRAINT "promotions_no_overlapping_active_category" EXCLUDE USING gist ("category" WITH =, tstzrange("starts_at", "ends_at") WITH &&) WHERE ("status" = 'active' AND "category" IS NOT NULL);
-- pricing_rules is the one table whose writer is a person at a psql prompt, so its audit
-- timestamp cannot wait for an application to set it (ADR-0004).
CREATE FUNCTION pricing_rules_touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
CREATE TRIGGER pricing_rules_set_updated_at BEFORE UPDATE ON "pricing_rules" FOR EACH ROW EXECUTE FUNCTION pricing_rules_touch_updated_at();
-- The reconciler sweeps from a watermark, so the single row has to exist before it first runs.
INSERT INTO "reconciler_state" ("id") VALUES (true) ON CONFLICT DO NOTHING;

-- 0001_seed_pricing_rules.sql
-- The three ingestion rules of the case study (issue #9), as json-rules-engine documents. They
-- live in the database rather than in a TypeScript constant so they change without a deploy;
-- higher priority runs first, so the markup lands before the bulk discount and the commission.
-- These rows fix the event vocabulary the ingestion wrapper of #39 must compile: an
-- `adjustPercentBps` event with a signed basis-point `value`, and facts drawn from the vendor
-- row (`category`, `stockQuantity`, `vendorPriceCents`). A rule the wrapper cannot parse stops
-- the whole job by design, so the two sides have to agree exactly.
-- Only the ingestion layer is seeded; the promotion-layer rules belong to the resolver (#36).
-- ON CONFLICT keeps a hand-applied re-run from doubling a markup.
--
-- The category match is exact and case-sensitive, and `Electronics` with a capital E is issue
-- #9's spelling. That is a data decision, not a constraint: a vendor file that spells the
-- category differently needs this row edited, not the code changed.
INSERT INTO "pricing_rules" ("type", "name", "conditions", "event", "priority")
VALUES
  (
    'ingestion',
    'electronics category markup',
    '{"all":[{"fact":"category","operator":"equal","value":"Electronics"}]}',
    '{"type":"adjustPercentBps","params":{"value":1500}}',
    30
  ),
  (
    'ingestion',
    'bulk stock discount',
    '{"all":[{"fact":"stockQuantity","operator":"greaterThan","value":100}]}',
    '{"type":"adjustPercentBps","params":{"value":-300}}',
    20
  ),
  (
    -- Every row: the commission applies to the whole catalogue. A per-vendor commission would
    -- need a `vendor` fact the chunk processor does not supply, and is its own story.
    'ingestion',
    'vendor commission',
    '{"all":[{"fact":"vendorPriceCents","operator":"greaterThanInclusive","value":0}]}',
    '{"type":"adjustPercentBps","params":{"value":500}}',
    10
  )
ON CONFLICT ("name") DO NOTHING;

-- 0002_active_promotions.sql
CREATE VIEW "public"."active_promotions" AS (select "id", "name", "discount_type", "value", "starts_at", "ends_at", "product_id", "category", "status", "created_at", "cancelled_at" from "promotions" where "promotions"."status" = 'active' and tstzrange("promotions"."starts_at", "promotions"."ends_at") @> now());
